#!/bin/sh

echo '###############################'
echo '##                           ##'
echo '##   📦 Install packages     ##'
echo '##                           ##'
echo '###############################'
echo

if ! builtin type -p 'yay' >/dev/null 2>&1; then
  CWD=`pwd`
  echo '🥣 Installing yay'
  tmpdir="$(command mktemp -d)"
  command cd "${tmpdir}" || return 1
  sudo pacman -Sy --needed --noconfirm base base-devel git
  git clone https://aur.archlinux.org/yay-bin.git
  cd yay-bin
  makepkg -si
  cd $CWD
fi

echo '📦 Installing base packages'
yay --noconfirm

echo '📦 Installing packages'
curl -Lks https://raw.githubusercontent.com/tomdevelops/arch-post-install/main/packages.csv | tail -n +2 | cut -d, -f1 | yay -Sy --noconfirm -

# echo 'Configuring dotfiles'
# if [ "$1" != "ssh" ]
# then
#  # Use https instead of ssh
#  curl -Lks https://raw.githubusercontent.com/tomdevelops/dotfiles/arch/setup | /bin/bash
#else
#  curl -Lks https://raw.githubusercontent.com/tomdevelops/dotfiles/arch/setup | /bin/bash -s ssh
#fi

echo
echo '🧹 Cleaning up unwanted packages'
yay -Qtdq | yay -Rns --noconfirm - 2>/dev/null
echo

echo
echo '###################################################'
echo '##                                               ##'
echo '##          👏 Installation Complete             ##'
echo '##      reboot to use the new configurations     ##'
echo '##                                               ##'
echo '###################################################'
echo
